/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { StoryService } from "../story.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { StoryCreateInput } from "./StoryCreateInput";
import { Story } from "./Story";
import { StoryFindManyArgs } from "./StoryFindManyArgs";
import { StoryWhereUniqueInput } from "./StoryWhereUniqueInput";
import { StoryUpdateInput } from "./StoryUpdateInput";
import { PageFindManyArgs } from "../../page/base/PageFindManyArgs";
import { Page } from "../../page/base/Page";
import { PageWhereUniqueInput } from "../../page/base/PageWhereUniqueInput";
import { ChoiceFindManyArgs } from "../../choice/base/ChoiceFindManyArgs";
import { Choice } from "../../choice/base/Choice";
import { ChoiceWhereUniqueInput } from "../../choice/base/ChoiceWhereUniqueInput";
import { AiInteractionFindManyArgs } from "../../aiInteraction/base/AiInteractionFindManyArgs";
import { AiInteraction } from "../../aiInteraction/base/AiInteraction";
import { AiInteractionWhereUniqueInput } from "../../aiInteraction/base/AiInteractionWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class StoryControllerBase {
  constructor(
    protected readonly service: StoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Story })
  @nestAccessControl.UseRoles({
    resource: "Story",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createStory(@common.Body() data: StoryCreateInput): Promise<Story> {
    return await this.service.createStory({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        summary: true,
        author: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Story] })
  @ApiNestedQuery(StoryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Story",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async stories(@common.Req() request: Request): Promise<Story[]> {
    const args = plainToClass(StoryFindManyArgs, request.query);
    return this.service.stories({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        summary: true,
        author: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Story })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Story",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async story(
    @common.Param() params: StoryWhereUniqueInput
  ): Promise<Story | null> {
    const result = await this.service.story({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        summary: true,
        author: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Story })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Story",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateStory(
    @common.Param() params: StoryWhereUniqueInput,
    @common.Body() data: StoryUpdateInput
  ): Promise<Story | null> {
    try {
      return await this.service.updateStory({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          summary: true,
          author: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Story })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Story",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteStory(
    @common.Param() params: StoryWhereUniqueInput
  ): Promise<Story | null> {
    try {
      return await this.service.deleteStory({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          summary: true,
          author: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/pages")
  @ApiNestedQuery(PageFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Page",
    action: "read",
    possession: "any",
  })
  async findPages(
    @common.Req() request: Request,
    @common.Param() params: StoryWhereUniqueInput
  ): Promise<Page[]> {
    const query = plainToClass(PageFindManyArgs, request.query);
    const results = await this.service.findPages(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        content: true,
        imageUrl: true,

        story: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/pages")
  @nestAccessControl.UseRoles({
    resource: "Story",
    action: "update",
    possession: "any",
  })
  async connectPages(
    @common.Param() params: StoryWhereUniqueInput,
    @common.Body() body: PageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pages: {
        connect: body,
      },
    };
    await this.service.updateStory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/pages")
  @nestAccessControl.UseRoles({
    resource: "Story",
    action: "update",
    possession: "any",
  })
  async updatePages(
    @common.Param() params: StoryWhereUniqueInput,
    @common.Body() body: PageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pages: {
        set: body,
      },
    };
    await this.service.updateStory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/pages")
  @nestAccessControl.UseRoles({
    resource: "Story",
    action: "update",
    possession: "any",
  })
  async disconnectPages(
    @common.Param() params: StoryWhereUniqueInput,
    @common.Body() body: PageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pages: {
        disconnect: body,
      },
    };
    await this.service.updateStory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/choices")
  @ApiNestedQuery(ChoiceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Choice",
    action: "read",
    possession: "any",
  })
  async findChoices(
    @common.Req() request: Request,
    @common.Param() params: StoryWhereUniqueInput
  ): Promise<Choice[]> {
    const query = plainToClass(ChoiceFindManyArgs, request.query);
    const results = await this.service.findChoices(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        nextPage: true,

        story: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/choices")
  @nestAccessControl.UseRoles({
    resource: "Story",
    action: "update",
    possession: "any",
  })
  async connectChoices(
    @common.Param() params: StoryWhereUniqueInput,
    @common.Body() body: ChoiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      choices: {
        connect: body,
      },
    };
    await this.service.updateStory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/choices")
  @nestAccessControl.UseRoles({
    resource: "Story",
    action: "update",
    possession: "any",
  })
  async updateChoices(
    @common.Param() params: StoryWhereUniqueInput,
    @common.Body() body: ChoiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      choices: {
        set: body,
      },
    };
    await this.service.updateStory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/choices")
  @nestAccessControl.UseRoles({
    resource: "Story",
    action: "update",
    possession: "any",
  })
  async disconnectChoices(
    @common.Param() params: StoryWhereUniqueInput,
    @common.Body() body: ChoiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      choices: {
        disconnect: body,
      },
    };
    await this.service.updateStory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/aiInteractions")
  @ApiNestedQuery(AiInteractionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AiInteraction",
    action: "read",
    possession: "any",
  })
  async findAiInteractions(
    @common.Req() request: Request,
    @common.Param() params: StoryWhereUniqueInput
  ): Promise<AiInteraction[]> {
    const query = plainToClass(AiInteractionFindManyArgs, request.query);
    const results = await this.service.findAiInteractions(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        query: true,
        response: true,

        story: {
          select: {
            id: true,
          },
        },

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/aiInteractions")
  @nestAccessControl.UseRoles({
    resource: "Story",
    action: "update",
    possession: "any",
  })
  async connectAiInteractions(
    @common.Param() params: StoryWhereUniqueInput,
    @common.Body() body: AiInteractionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      aiInteractions: {
        connect: body,
      },
    };
    await this.service.updateStory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/aiInteractions")
  @nestAccessControl.UseRoles({
    resource: "Story",
    action: "update",
    possession: "any",
  })
  async updateAiInteractions(
    @common.Param() params: StoryWhereUniqueInput,
    @common.Body() body: AiInteractionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      aiInteractions: {
        set: body,
      },
    };
    await this.service.updateStory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/aiInteractions")
  @nestAccessControl.UseRoles({
    resource: "Story",
    action: "update",
    possession: "any",
  })
  async disconnectAiInteractions(
    @common.Param() params: StoryWhereUniqueInput,
    @common.Body() body: AiInteractionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      aiInteractions: {
        disconnect: body,
      },
    };
    await this.service.updateStory({
      where: params,
      data,
      select: { id: true },
    });
  }
}
