/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { PageUpdateManyWithoutStoriesInput } from "./PageUpdateManyWithoutStoriesInput";
import { Type } from "class-transformer";
import { ChoiceUpdateManyWithoutStoriesInput } from "./ChoiceUpdateManyWithoutStoriesInput";
import { AiInteractionUpdateManyWithoutStoriesInput } from "./AiInteractionUpdateManyWithoutStoriesInput";

@InputType()
class StoryUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  summary?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  author?: string | null;

  @ApiProperty({
    required: false,
    type: () => PageUpdateManyWithoutStoriesInput,
  })
  @ValidateNested()
  @Type(() => PageUpdateManyWithoutStoriesInput)
  @IsOptional()
  @Field(() => PageUpdateManyWithoutStoriesInput, {
    nullable: true,
  })
  pages?: PageUpdateManyWithoutStoriesInput;

  @ApiProperty({
    required: false,
    type: () => ChoiceUpdateManyWithoutStoriesInput,
  })
  @ValidateNested()
  @Type(() => ChoiceUpdateManyWithoutStoriesInput)
  @IsOptional()
  @Field(() => ChoiceUpdateManyWithoutStoriesInput, {
    nullable: true,
  })
  choices?: ChoiceUpdateManyWithoutStoriesInput;

  @ApiProperty({
    required: false,
    type: () => AiInteractionUpdateManyWithoutStoriesInput,
  })
  @ValidateNested()
  @Type(() => AiInteractionUpdateManyWithoutStoriesInput)
  @IsOptional()
  @Field(() => AiInteractionUpdateManyWithoutStoriesInput, {
    nullable: true,
  })
  aiInteractions?: AiInteractionUpdateManyWithoutStoriesInput;
}

export { StoryUpdateInput as StoryUpdateInput };
