/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { PageCreateNestedManyWithoutStoriesInput } from "./PageCreateNestedManyWithoutStoriesInput";
import { Type } from "class-transformer";
import { ChoiceCreateNestedManyWithoutStoriesInput } from "./ChoiceCreateNestedManyWithoutStoriesInput";
import { AiInteractionCreateNestedManyWithoutStoriesInput } from "./AiInteractionCreateNestedManyWithoutStoriesInput";

@InputType()
class StoryCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  summary?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  author?: string | null;

  @ApiProperty({
    required: false,
    type: () => PageCreateNestedManyWithoutStoriesInput,
  })
  @ValidateNested()
  @Type(() => PageCreateNestedManyWithoutStoriesInput)
  @IsOptional()
  @Field(() => PageCreateNestedManyWithoutStoriesInput, {
    nullable: true,
  })
  pages?: PageCreateNestedManyWithoutStoriesInput;

  @ApiProperty({
    required: false,
    type: () => ChoiceCreateNestedManyWithoutStoriesInput,
  })
  @ValidateNested()
  @Type(() => ChoiceCreateNestedManyWithoutStoriesInput)
  @IsOptional()
  @Field(() => ChoiceCreateNestedManyWithoutStoriesInput, {
    nullable: true,
  })
  choices?: ChoiceCreateNestedManyWithoutStoriesInput;

  @ApiProperty({
    required: false,
    type: () => AiInteractionCreateNestedManyWithoutStoriesInput,
  })
  @ValidateNested()
  @Type(() => AiInteractionCreateNestedManyWithoutStoriesInput)
  @IsOptional()
  @Field(() => AiInteractionCreateNestedManyWithoutStoriesInput, {
    nullable: true,
  })
  aiInteractions?: AiInteractionCreateNestedManyWithoutStoriesInput;
}

export { StoryCreateInput as StoryCreateInput };
