/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AiInteractionService } from "../aiInteraction.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AiInteractionCreateInput } from "./AiInteractionCreateInput";
import { AiInteraction } from "./AiInteraction";
import { AiInteractionFindManyArgs } from "./AiInteractionFindManyArgs";
import { AiInteractionWhereUniqueInput } from "./AiInteractionWhereUniqueInput";
import { AiInteractionUpdateInput } from "./AiInteractionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AiInteractionControllerBase {
  constructor(
    protected readonly service: AiInteractionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AiInteraction })
  @nestAccessControl.UseRoles({
    resource: "AiInteraction",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAiInteraction(
    @common.Body() data: AiInteractionCreateInput
  ): Promise<AiInteraction> {
    return await this.service.createAiInteraction({
      data: {
        ...data,

        story: data.story
          ? {
              connect: data.story,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        query: true,
        response: true,

        story: {
          select: {
            id: true,
          },
        },

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AiInteraction] })
  @ApiNestedQuery(AiInteractionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AiInteraction",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async aiInteractions(
    @common.Req() request: Request
  ): Promise<AiInteraction[]> {
    const args = plainToClass(AiInteractionFindManyArgs, request.query);
    return this.service.aiInteractions({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        query: true,
        response: true,

        story: {
          select: {
            id: true,
          },
        },

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AiInteraction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AiInteraction",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async aiInteraction(
    @common.Param() params: AiInteractionWhereUniqueInput
  ): Promise<AiInteraction | null> {
    const result = await this.service.aiInteraction({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        query: true,
        response: true,

        story: {
          select: {
            id: true,
          },
        },

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AiInteraction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AiInteraction",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAiInteraction(
    @common.Param() params: AiInteractionWhereUniqueInput,
    @common.Body() data: AiInteractionUpdateInput
  ): Promise<AiInteraction | null> {
    try {
      return await this.service.updateAiInteraction({
        where: params,
        data: {
          ...data,

          story: data.story
            ? {
                connect: data.story,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          query: true,
          response: true,

          story: {
            select: {
              id: true,
            },
          },

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AiInteraction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AiInteraction",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAiInteraction(
    @common.Param() params: AiInteractionWhereUniqueInput
  ): Promise<AiInteraction | null> {
    try {
      return await this.service.deleteAiInteraction({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          query: true,
          response: true,

          story: {
            select: {
              id: true,
            },
          },

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
